-- MySQL Script generated by MySQL Workbench
-- Tue Oct  1 20:34:34 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema stockup
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema stockup
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `stockup` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `stockup` ;

-- -----------------------------------------------------
-- Table `stockup`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stockup`.`categorias` (
  `idcategorias` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idcategorias`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `stockup`.`fornecedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stockup`.`fornecedores` (
  `idfornecedores` INT NOT NULL,
  `razao_social` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idfornecedores`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `stockup`.`manager`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stockup`.`manager` (
  `idmanager` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(20) NOT NULL,
  `cnpj` VARCHAR(15) NOT NULL,
  `email` VARCHAR(30) NOT NULL,
  `senha` VARCHAR(20) NOT NULL,
  `manager_type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idmanager`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `stockup`.`produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stockup`.`produtos` (
  `idprodutos` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NOT NULL,
  `SKU` VARCHAR(45) NOT NULL,
  `qtd_estoque` INT NOT NULL,
  `idmanager` INT NULL DEFAULT NULL,
  `idcategoria` INT NULL DEFAULT NULL,
  `preco_unitario` DECIMAL(10,0) NULL DEFAULT NULL,
  PRIMARY KEY (`idprodutos`),
  INDEX `fk_categorias_produtos_idx` (`idcategoria` ASC) VISIBLE,
  INDEX `idmanager` (`idmanager` ASC) VISIBLE,
  CONSTRAINT `idcategoria`
    FOREIGN KEY (`idcategoria`)
    REFERENCES `stockup`.`categorias` (`idcategorias`),
  CONSTRAINT `idmanager`
    FOREIGN KEY (`idmanager`)
    REFERENCES `stockup`.`manager` (`idmanager`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `stockup`.`fornecedor_produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stockup`.`fornecedor_produtos` (
  `idproduto` INT NOT NULL,
  `idfornecedor` INT NOT NULL,
  `data_validade` DATE NOT NULL,
  `data_entrada` DATE NOT NULL,
  `qtd` INT NOT NULL,
  PRIMARY KEY (`idproduto`, `idfornecedor`),
  INDEX `idfornecedor_idx` (`idfornecedor` ASC) VISIBLE,
  CONSTRAINT `fkfornecedor`
    FOREIGN KEY (`idfornecedor`)
    REFERENCES `stockup`.`fornecedores` (`idfornecedores`)
    ON UPDATE CASCADE,
  CONSTRAINT `fkproduto`
    FOREIGN KEY (`idproduto`)
    REFERENCES `stockup`.`produtos` (`idprodutos`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `stockup`.`funcionarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stockup`.`funcionarios` (
  `idfuncionario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `email` VARCHAR(30) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idfuncionario`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `stockup`.`vendas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stockup`.`vendas` (
  `idvendas` INT NOT NULL AUTO_INCREMENT,
  `valor_venda` DECIMAL(10,0) NOT NULL,
  `data_venda` VARCHAR(45) NOT NULL,
  `idfuncionario` INT NOT NULL,
  PRIMARY KEY (`idvendas`),
  INDEX `idfuncionario_idx` (`idfuncionario` ASC) VISIBLE,
  CONSTRAINT `idfuncionario`
    FOREIGN KEY (`idfuncionario`)
    REFERENCES `stockup`.`funcionarios` (`idfuncionario`))
ENGINE = InnoDB
AUTO_INCREMENT = 64
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `stockup`.`venda_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stockup`.`venda_produto` (
  `idvenda` INT NOT NULL,
  `idproduto` INT NOT NULL,
  `qtd_produto` INT NOT NULL,
  PRIMARY KEY (`idvenda`, `idproduto`),
  INDEX `idproduto_idx` (`idproduto` ASC) VISIBLE,
  CONSTRAINT `idproduto`
    FOREIGN KEY (`idproduto`)
    REFERENCES `stockup`.`produtos` (`idprodutos`),
  CONSTRAINT `idvenda`
    FOREIGN KEY (`idvenda`)
    REFERENCES `stockup`.`vendas` (`idvendas`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
